"""Add is_good_weather column

Revision ID: 8942067c11c1
Revises: cc92f1620547
Create Date: 2025-04-10 04:08:24.265092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8942067c11c1'
down_revision: Union[str, None] = 'cc92f1620547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sun_info', sa.Column('is_good_weather', sa.Boolean(), nullable=True))
    op.alter_column('sun_info', 'weather_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sun_info', 'sunrise',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('sun_info', 'sunset',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.drop_column('sun_info', 'is_day')
    op.alter_column('weather', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('weather', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('weather', 'wind_degree')
    op.drop_column('weather', 'sunrise')
    op.drop_column('weather', 'wind_direction')
    op.drop_column('weather', 'wind_kph')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('wind_kph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('weather', sa.Column('wind_direction', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('weather', sa.Column('sunrise', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('weather', sa.Column('wind_degree', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('weather', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('weather', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('sun_info', sa.Column('is_day', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('sun_info', 'sunset',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('sun_info', 'sunrise',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('sun_info', 'weather_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('sun_info', 'is_good_weather')
    # ### end Alembic commands ###
